name: Postman Collection Workflow

permissions:
  contents: write

on:
  push:
    branches:
      - main

  workflow_dispatch:

  schedule:
    - cron: "30 02 * * *"    # 8:00 AM IST Every Day
    - cron: "00 14 * * *"    # 7:30 PM IST Every Day
    - cron: "00 06 * * 1-5"  # 11:30 AM IST Monday to Friday

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install Newman and HTML Extra Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run Postman Collection
        run: |
          mkdir -p newman

          newman run "Newman - Inwarranty-flow Collection(Jatin's collection).postman_collection.json" \
          -e "QA.postman_environment.json" \
          -d "testdata.csv" \
          -r cli,htmlextra \
          --reporter-htmlextra-export "newman/index.html"

      - name: Verify Report
        if: always()
        run: |
          echo "Generated files:"
          ls -R newman

      - name: Upload Newman Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Newman-Report
          path: newman/

      - name: Deploy to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./newman

      - name: Sending the Email Notifications
        if: always()
        uses: dawidd6/action-send-mail@v18
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Phoenix Inwarrenty Flow Collection Test Execution Report Notification
          to: sheebanigam@gmail.com
          from: ${{ secrets.EMAIL_USERNAME }}
          body: | 
                Hi,
                Phoenix inwarrenty flow collection has been executed and report is generated successfully as well.
                Find the attached link to view the report.
                https://s123nigam.github.io/Phoenix-Inwarrenty-Flow-Collection/

          
          

        












          
